# 网络相关配置,按网络名分节。
# exp.yaml 中各实验通过 network: <name> 引用对应网络。

slowfast:
  model: slowfast
  decode_mode: beam
  model_args:
    num_classes: 1296
    hidden_size: 1024
    c2d_type: slowfast101 #resnet18, mobilenet_v2, squeezenet1_1, shufflenet_v2_x1_0, efficientnet_b1, mnasnet1_0, regnet_y_800mf, vgg16_bn, vgg11_bn, regnet_x_800mf, regnet_x_400mf, densenet121, regnet_y_1_6gf
    conv_type: 2
    kernel_size: ['K5', "P2", 'K5', "P2"]
    use_bn: 1
    # SMKD
    share_classifier: 1
    weight_norm: True
    slowfast_config: SLOWFAST_64x2_R101_50_50.yaml
  loss_weights:
    ConvCTC: 1.0
    SeqCTC: 1.0
    Dist: 25.0
    Cu: 0.001
    Cp: 0.001
    Slow: 1.0
    Fast: 1.0

tlp:
  model: tlp
  decode_mode: beam
  model_args:
    num_classes: 1
    c2d_type: resnet18
    kernel_size: ['K5', 'P2', 'K5', 'P2']
    stride: [4, 0]
    use_bn: 1
  loss_weights:
    ConvCTC: 1.0
    SeqCTC: 1.0
    Dist: 25.0
    Cu: 0.001
    Cp: 0.001

vac:
  model: vac
  decode_mode: beam
  model_args:
    num_classes: 1296
    c2d_type: resnet18
    kernel_size: ['K5', "P2", 'K5', "P2"]
    stride: [4, 0]
    use_bn: 1
  loss_weights:
    ConvCTC: 1.0
    SeqCTC: 1.0
    Dist: 25.0
